# Generated by Django 3.2.2 on 2021-05-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_aniversario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='aniversario',
            field=models.DateField(),
        ),
    ]
